### 회원 등록
POST localhost:8080/members
Content-Type: application/json

{
  "id": "testId",
  "password": "testPassword",
  "email": "test@email.com"
}

### 회원 탈퇴 전환
PUT localhost:8080/members/1/quit
Content-Type: application/json


### 회원 휴면상태 전환
PUT localhost:8080/members/1/sleep
Content-Type: application/json

### 회원 이메일, 비밀번호 수정
PUT localhost:8080/members/1
Content-Type: application/json

{
  "email": "update22@email.com",
  "password": "sdfdsfsdf"
}

$2a$10$Sz4M0PXkFl8EtGbqWNsXceF01tEjCkKWShy/t8VyoPKpNLd6cmpse
$2a$10$I4ZG/bZUByYu2aTVql/3LekOHGybu5z7Lb1bG6hxzRFH1ftonRv7m