### 회원 등록
POST localhost:8080/members
Content-Type: application/json

{
  "id": "testId5",
  "password": "testPassword",
  "email": "test@email.com123"
}

### 회원 탈퇴 전환
@memberId = 1
PUT localhost:8080/members/{{memberId}}/quit

### 회원 휴면 전환
PUT localhost:8080/members/{{memberId}}/sleep

### 회원 활동 전환
PUT localhost:8080/members/{{memberId}}/active


### 회원 이메일, 비밀번호 수정
PUT localhost:8080/members/{{memberId}}
Content-Type: application/json

{
  "email": "update11@email.com",
  "password": "testPassword"
}

###
POST localhost:8080/login/process
Content-Type: application/json

{
  "id": "testId5",
  "password": "testPassword"
}