### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원 수정
PUT localhost:8080/members/hi
Content-Type: application/json

{
 "id" : "hi",
 "password" : "hi",
 "email" : "m@n.com"
}